# Generated by Django 2.2.4 on 2019-08-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('project', 'name')},
        ),
    ]
